

services:
  backend:
    build: ./backend
    container_name: employee-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data: